# openapi2-functions.yaml
swagger: '2.0'
info:
  title: hello-world-gnfuczqb description
  description: Sample API on API Gateway with a Google Cloud Functions backend
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
paths:
  /hello:
    get:
      summary: Greet a user
      operationId: hello
      x-google-backend:
        address: https://us-central1-qwiklabs-gcp-04-7944742518b9.cloudfunctions.net/helloGET
      responses:
       '200':
          description: A successful response
          schema:
            type: string